version: "3.7"
services:
  backend:
    image: water0641/ticket-backend:main
    container_name: backend
    hostname: backend
    expose:
      - "5000"
  front:
    image: water0641/ticket-front:main
    container_name: front
    ports:
      - "3000:3000"
  admin:
    image: water0641/ticket-admin:main
    container_name: admin
    expose:
      - "3100"
  nginx:
    depends_on:
      - backend
      - front
      - admin
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"
